### ISSUE TITLE
"Issueベースの開発"レビュー依頼

### ISSUE THREAD

**Issue by msteq** [msteq/SunUpHabits#34]
■Webアプリの概要
「SunUpHabits」は、モーニングルーティンに特化した習慣化サポートWEBアプリです。ユーザーは自分の朝のルーティンを投稿し、他のユーザーと進捗を共有できます。また、タイムラインで他のユーザーのルーティンや成果を確認し、リアクションやコメントを通じて相互にサポートし合うことで、朝の習慣を続けやすくし、ポジティブな一日をスタートすることができます。

■1週間辺りの開発に向けられる時間
- 1週間あたり：40時間

（ストーリポイント1消費するのに2時間を目安として、1週間あたりどれだけストーリポイントを消化できるか確認してください）

■ProjectsのURL
https://github.com/users/msteq/projects/1/views/1

■MVPリリースまで
- [ ] ユーザー登録機能
- [ ] ログイン/ログアウト機能
- [ ] マイページ機能
- [ ] 習慣登録/投稿/編集/削除機能
- [ ] 一覧画面
- [ ] 詳細画面

■MVP後
- [ ] コメント機能
- [ ] いいね機能
- [ ] 検索機能
- [ ] パスワードリセット機能
- [ ] 達成率進捗可視化機能

■MVPレビュー依頼予定日
予定日：2024年11月30日

**Comment by kenchasonakai** [comment]
LGTMです！
