### ISSUE TITLE
"MVPリリース"レビュー依頼

### ISSUE THREAD

**Issue by msteq** [msteq/SunUpHabits#59]
## 各種情報
サービスの概要とMVPで検証する事柄：「SunUpHabits」は、モーニングルーティンに特化した習慣化サポートWEBアプリです。ユーザーは自分の朝のルーティンを投稿し、他のユーザーと進捗を共有できます。また、タイムラインで他のユーザーのルーティンや成果を確認し、リアクションやコメントを通じて相互にサポートし合うことで、朝の習慣を続けやすくし、ポジティブな一日をスタートすることができます。
サービス名：SunUpHabits
サービスURL：https://sunuphabits.onrender.com/

## READMEレビュー時にMVPリリース時点で実装予定だった機能
■MVPリリースまで
- [x] ユーザー登録機能
- [x] ログイン/ログアウト機能
- [ ] マイページ機能
- [x] 習慣登録/投稿/編集/削除機能
- [x] 一覧画面
- [x] 詳細画面

■MVP後
- [ ] コメント機能
- [ ] いいね機能
- [x] 検索機能
- [ ] パスワードリセット機能
- [x] 達成率進捗可視化機能

## READMEレビュー時から変更した機能
・マイページ機能については、「卒業認定までの開発スケジュール見積もり面談」で富田講師と面談し、MVP後に実装することになりました。
・検索機能はMVP後に実装予定でしたが、投稿一覧画面実装時に合わせて実装しました。
・達成率進捗可視化機能はMVP後に実装予定でしたが、習慣詳細画面実装時に合わせて実装しました。

## サービスイメージがわかるようなスクリーンショット等
トップページ
[![Image from Gyazo](https://i.gyazo.com/6a11758eb19136e6b4f6c2d9ca5fa248.jpg)](https://gyazo.com/6a11758eb19136e6b4f6c2d9ca5fa248)

新規登録画面
[![Image from Gyazo](https://i.gyazo.com/ff1e4e0583b3bcb3233c041a5aa02c15.png)](https://gyazo.com/ff1e4e0583b3bcb3233c041a5aa02c15)

ログイン画面
[![Image from Gyazo](https://i.gyazo.com/ed227ec67acf4c8f9c4233d228c0b3aa.png)](https://gyazo.com/ed227ec67acf4c8f9c4233d228c0b3aa)

新規習慣登録画面
[![Image from Gyazo](https://i.gyazo.com/7ea8295312a60aaa7f129e22085988da.png)](https://gyazo.com/7ea8295312a60aaa7f129e22085988da)

習慣詳細画面
[![Image from Gyazo](https://i.gyazo.com/9f82b8a7fd8512ec742974ffed4be398.png)](https://gyazo.com/9f82b8a7fd8512ec742974ffed4be398)

習慣編集画面
[![Image from Gyazo](https://i.gyazo.com/b8e8a36b475d686b946e1028c2472c34.png)](https://gyazo.com/b8e8a36b475d686b946e1028c2472c34)

投稿画面(達成を選択した場合)
[![Image from Gyazo](https://i.gyazo.com/753a69e9b26b8d4a64752c827c29ce12.png)](https://gyazo.com/753a69e9b26b8d4a64752c827c29ce12)

マイ習慣画面
[![Image from Gyazo](https://i.gyazo.com/bd7f590f4d7e471288d0ff605b976a3d.png)](https://gyazo.com/bd7f590f4d7e471288d0ff605b976a3d)

投稿一覧画面
[![Image from Gyazo](https://i.gyazo.com/60cf9d73330f28e4c45155481ac064af.png)](https://gyazo.com/60cf9d73330f28e4c45155481ac064af)

投稿詳細画面
[![Image from Gyazo](https://i.gyazo.com/809bb5f21cf5ff4dcd7445faf546c158.png)](https://gyazo.com/809bb5f21cf5ff4dcd7445faf546c158)

**Comment by kashiwagi-rena** [comment]
提出ありがとうございます！
新規登録時にエラーが出ているようです。確認してください。

https://github.com/user-attachments/assets/2f54da15-d8bb-464b-a06d-194d928ed1f6

**Comment by msteq** [comment]
お忙しい中ご確認いただきありがとうございます。
422エラーが出ないよう修正いたしましたので、改めてご確認の程、よろしくお願いいたします。

**Comment by bepmas** [comment]
機能確認が取れました。LGTMです。
引き続き本リリースに向けて開発頑張ってください。

以下、LGTMを出した方々に共通してお伝えしている内容になります。
（Webアプリを就職活動で活用される方向けの内容になります）

===== 本リリースまでに以下の項目を実装してください =====
□ 独自ドメイン反映
    -> DNSやSSLの対応も必要になるのでアピールになり、URLを書類等に記載するときの見栄えも良くなります。
□ OGP（静的 or 動的）
    -> SNS等でシェアするときの見栄えが良くなります。Webアプリであればどんなアプリでも取り入れられるので対応しておきましょう。
□ RSpec（モデルテスト+システムテスト or モデルテスト+リクエストテスト）
    -> 開発における品質の意識や開発効率の意識の高さをアピールできます。Request Specをメインに最低限各機能に正常にアクセスできるか程度はテストで確認できるようにしておきましょう。
□ CI（GitHubActions）
    -> 実際に開発現場でも使われており、アプリ外で技術のアピールが出来るものです。RSpecと合わせて実装を行いましょう。
□ Rubocopを使ってのリファクタリング
    -> Lintチェックツールは開発現場で広く使われています。コードのLintを整えておくことはチームで開発することを意識するうえでとても大切になるので取り入れておきましょう。

他のプログラミング学習者のWebアプリと異なることをアピールするために、よりインパクトのある機能を複数盛り込むことが重要になってきます。
□ SNSログイン（Google or LINE）
    -> ほとんどのアプリに取り入れられてユーザー体験の向上や技術のアピールにつながるので取り入れましょう。
□ 検索機能のアップデート（オートコンプリート、マルチ検索等）   ※検索機能がある場合
    -> 特にオートコンプリートは検索体験の向上だけではなくJS系の技術も取り入れていることをアピール出来るので積極的に取り入れましょう。

ユーザー体験という面では以下の項目も大切です。
□ オートログイン
    -> ユーザー登録後に再度ログイン操作を行わせないことでユーザー体験を向上させられます。
□ 使い方説明がある
    -> 初めて訪れたユーザーに呈して使い方の説明があることで体験を向上させられます。
□ レスポンシブ対応
    -> いずれのデバイスでも綺麗にサービスが活用できることで体験が良くなります。
□ 利用規約・プライバシーポリシーを未ログイン状態でも確認できる
    -> 利用規約・プライバシーポリシーがあることで、ちゃんとしたサービスという印象を与えられます。
□ ローディングアニメーション（処理が重い箇所）
    -> 処理が重い箇所に何の対応も無いとユーザーが正しく操作できたのか困惑してしまいます。そうした際はローディングアニメーションを表示させることで体験が向上します。
